export enum DrawingStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REVISION_REQUIRED = 'REVISION_REQUIRED',
  RESUBMITTED = 'RESUBMITTED',
  APPROVED = 'APPROVED',
}

export enum RFIStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  ANSWERED = 'ANSWERED',
  CLOSED = 'CLOSED',
}

export enum MaterialsRequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ORDERED = 'ORDERED',
  PARTIALLY_DELIVERED = 'PARTIALLY_DELIVERED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum DelayCause {
  WEATHER = 'WEATHER',
  MATERIALS = 'MATERIALS',
  LABOUR = 'LABOUR',
  DESIGN = 'DESIGN',
  CLIENT = 'CLIENT',
  UTILITIES = 'UTILITIES',
  OTHER = 'OTHER',
}

export enum FileFolder {
  DRAWINGS = 'DRAWINGS',
  CONTRACTS = 'CONTRACTS',
  PERMITS = 'PERMITS',
  REPORTS = 'REPORTS',
  OTHER = 'OTHER',
}
